name: "Podcast Generator"
author: "Juan-Luke Van Wyk"
description: "Generates a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  colour: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actior }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actior }}